### ISSUE TITLE
Habla unassigned

### ISSUE THREAD

**Issue by slytter** [bitkompagniet/habla#61]
A similar program that shows all unassigned issues

**Comment by kparkov** [comment]
Remember to refactor the code so you can re-use the requests and central logic. It makes sense that `habla todo`, `habla unassigned` and `habla tasks` reuse the same function with different parameters.

I also strongly advise you to refactor `fetch-data.js`, and split it up into nice and clean interfaces (preferrably 3 files) for the remote API's.
