### ISSUE TITLE
Some issues not found

### ISSUE THREAD

**Issue by kparkov** [bitkompagniet/habla#80]
I am still not seeing all of my issues. I have a milestone deadline on Gitlab today (Mar 28), but the issue associated is not shown in the list. To reproduce, try to create a milestone in Gitlab with a deadline, and add a single issue _without_ deadline to it, where you are assigned. 

It should now be shown in the issue list with the deadline. In my case, it is not.

**Comment by kparkov** [comment]
I think this will be much easier to debug when #74 has been done.

**Comment by slytter** [comment]
Might be caused by Gitlabs  [pagination](https://docs.gitlab.com/ee/api/README.html#pagination)

**Comment by kparkov** [comment]
I will test whether I am still seeing this as soon as you have merged the pagination stuff into master, @neheren?
